global:
  catalog: serverless_stable_14ey07_catalog
  schema: mbi
  workspace_url: https://fevm-serverless-stable-14ey07.cloud.databricks.com

# usecase1:
#   file_description_path: vol1/source/usecase1/supporting_files/usecase1-purpose.csv

ingestion:
  source_volume_path: vol1/source/usecase2/input_pdf_files/
  entities_table: entities_uc2
  bronze_layer:
    metadata_extraction_llm: databricks-claude-opus-4-6
    bronze_table: docs_bronze_uc2
  silver_layer:
    parsed_document_table: docs_silver_parsed_docs_raw_uc2
    document_elements_table: docs_silver_elements_uc2
    document_pages_table: docs_silver_pages_uc2
    image_output_path: vol1/parsed_doc_images/usecase2
  gold_layer:
    aggregated_pages_table: docs_gold_pages_uc2
    page_quality_rater_llm: databricks-claude-opus-4-6

  platinum_layer:
    summarization_llm: databricks-claude-opus-4-6

    summarization_prompt: |
      Summarize the following document chunk. Return a concise yet descriptive summary. RETURN ONLY THE SUMMARY AND NOTHING ELSE.
    platinum_table: docs_platinum_uc2
  
  vector_search:
    endpoint_name: vsi_mbi
    index_name: docs_platinum_uc2_index_mbi
    primary_key: chunk_id
    embedding_source_column: page_content_final
    embedding_model_endpoint: databricks-gte-large-en
    pipeline_type: TRIGGERED